artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://drive.google.com/file/d/12uJKQ_aOEEYpen2XJie583nceD5Tg73J/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/data.rar
  unzip_dir: artifacts/data_ingestion

